services:
  db:
    image: postgres:16-alpine
    container_name: hexacore_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hexacore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexacore_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/hexacore_db?schema=public"
      JWT_SECRET: "development_secret_key_123"
      PORT: 3000
      NODE_ENV: dev
    depends_on:
      - db

volumes:
  postgres_data:
