/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVeterinariosIndexRouteImport } from './routes/dashboard.veterinarios.index'
import { Route as DashboardTerrenosIndexRouteImport } from './routes/dashboard.terrenos.index'
import { Route as DashboardPropietariosIndexRouteImport } from './routes/dashboard.propietarios.index'
import { Route as DashboardGanadoIndexRouteImport } from './routes/dashboard.ganado.index'
import { Route as DashboardTerrenosIdRouteImport } from './routes/dashboard.terrenos.$id'
import { Route as DashboardPropietariosIdRouteImport } from './routes/dashboard.propietarios.$id'
import { Route as DashboardGanadoIdRouteImport } from './routes/dashboard.ganado.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVeterinariosIndexRoute =
  DashboardVeterinariosIndexRouteImport.update({
    id: '/veterinarios/',
    path: '/veterinarios/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTerrenosIndexRoute = DashboardTerrenosIndexRouteImport.update({
  id: '/terrenos/',
  path: '/terrenos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropietariosIndexRoute =
  DashboardPropietariosIndexRouteImport.update({
    id: '/propietarios/',
    path: '/propietarios/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGanadoIndexRoute = DashboardGanadoIndexRouteImport.update({
  id: '/ganado/',
  path: '/ganado/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTerrenosIdRoute = DashboardTerrenosIdRouteImport.update({
  id: '/terrenos/$id',
  path: '/terrenos/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropietariosIdRoute = DashboardPropietariosIdRouteImport.update({
  id: '/propietarios/$id',
  path: '/propietarios/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGanadoIdRoute = DashboardGanadoIdRouteImport.update({
  id: '/ganado/$id',
  path: '/ganado/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ganado/$id': typeof DashboardGanadoIdRoute
  '/dashboard/propietarios/$id': typeof DashboardPropietariosIdRoute
  '/dashboard/terrenos/$id': typeof DashboardTerrenosIdRoute
  '/dashboard/ganado/': typeof DashboardGanadoIndexRoute
  '/dashboard/propietarios/': typeof DashboardPropietariosIndexRoute
  '/dashboard/terrenos/': typeof DashboardTerrenosIndexRoute
  '/dashboard/veterinarios/': typeof DashboardVeterinariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ganado/$id': typeof DashboardGanadoIdRoute
  '/dashboard/propietarios/$id': typeof DashboardPropietariosIdRoute
  '/dashboard/terrenos/$id': typeof DashboardTerrenosIdRoute
  '/dashboard/ganado': typeof DashboardGanadoIndexRoute
  '/dashboard/propietarios': typeof DashboardPropietariosIndexRoute
  '/dashboard/terrenos': typeof DashboardTerrenosIndexRoute
  '/dashboard/veterinarios': typeof DashboardVeterinariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ganado/$id': typeof DashboardGanadoIdRoute
  '/dashboard/propietarios/$id': typeof DashboardPropietariosIdRoute
  '/dashboard/terrenos/$id': typeof DashboardTerrenosIdRoute
  '/dashboard/ganado/': typeof DashboardGanadoIndexRoute
  '/dashboard/propietarios/': typeof DashboardPropietariosIndexRoute
  '/dashboard/terrenos/': typeof DashboardTerrenosIndexRoute
  '/dashboard/veterinarios/': typeof DashboardVeterinariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/ganado/$id'
    | '/dashboard/propietarios/$id'
    | '/dashboard/terrenos/$id'
    | '/dashboard/ganado/'
    | '/dashboard/propietarios/'
    | '/dashboard/terrenos/'
    | '/dashboard/veterinarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/ganado/$id'
    | '/dashboard/propietarios/$id'
    | '/dashboard/terrenos/$id'
    | '/dashboard/ganado'
    | '/dashboard/propietarios'
    | '/dashboard/terrenos'
    | '/dashboard/veterinarios'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/ganado/$id'
    | '/dashboard/propietarios/$id'
    | '/dashboard/terrenos/$id'
    | '/dashboard/ganado/'
    | '/dashboard/propietarios/'
    | '/dashboard/terrenos/'
    | '/dashboard/veterinarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/veterinarios/': {
      id: '/dashboard/veterinarios/'
      path: '/veterinarios'
      fullPath: '/dashboard/veterinarios/'
      preLoaderRoute: typeof DashboardVeterinariosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/terrenos/': {
      id: '/dashboard/terrenos/'
      path: '/terrenos'
      fullPath: '/dashboard/terrenos/'
      preLoaderRoute: typeof DashboardTerrenosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/propietarios/': {
      id: '/dashboard/propietarios/'
      path: '/propietarios'
      fullPath: '/dashboard/propietarios/'
      preLoaderRoute: typeof DashboardPropietariosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ganado/': {
      id: '/dashboard/ganado/'
      path: '/ganado'
      fullPath: '/dashboard/ganado/'
      preLoaderRoute: typeof DashboardGanadoIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/terrenos/$id': {
      id: '/dashboard/terrenos/$id'
      path: '/terrenos/$id'
      fullPath: '/dashboard/terrenos/$id'
      preLoaderRoute: typeof DashboardTerrenosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/propietarios/$id': {
      id: '/dashboard/propietarios/$id'
      path: '/propietarios/$id'
      fullPath: '/dashboard/propietarios/$id'
      preLoaderRoute: typeof DashboardPropietariosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ganado/$id': {
      id: '/dashboard/ganado/$id'
      path: '/ganado/$id'
      fullPath: '/dashboard/ganado/$id'
      preLoaderRoute: typeof DashboardGanadoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGanadoIdRoute: typeof DashboardGanadoIdRoute
  DashboardPropietariosIdRoute: typeof DashboardPropietariosIdRoute
  DashboardTerrenosIdRoute: typeof DashboardTerrenosIdRoute
  DashboardGanadoIndexRoute: typeof DashboardGanadoIndexRoute
  DashboardPropietariosIndexRoute: typeof DashboardPropietariosIndexRoute
  DashboardTerrenosIndexRoute: typeof DashboardTerrenosIndexRoute
  DashboardVeterinariosIndexRoute: typeof DashboardVeterinariosIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGanadoIdRoute: DashboardGanadoIdRoute,
  DashboardPropietariosIdRoute: DashboardPropietariosIdRoute,
  DashboardTerrenosIdRoute: DashboardTerrenosIdRoute,
  DashboardGanadoIndexRoute: DashboardGanadoIndexRoute,
  DashboardPropietariosIndexRoute: DashboardPropietariosIndexRoute,
  DashboardTerrenosIndexRoute: DashboardTerrenosIndexRoute,
  DashboardVeterinariosIndexRoute: DashboardVeterinariosIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
