/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardRanchosIndexRouteImport } from './routes/dashboard.ranchos.index'
import { Route as DashboardPropietariosIndexRouteImport } from './routes/dashboard.propietarios.index'
import { Route as DashboardRanchosIdRouteImport } from './routes/dashboard.ranchos.$id'
import { Route as DashboardPropietariosIdRouteImport } from './routes/dashboard.propietarios.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRanchosIndexRoute = DashboardRanchosIndexRouteImport.update({
  id: '/ranchos/',
  path: '/ranchos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropietariosIndexRoute =
  DashboardPropietariosIndexRouteImport.update({
    id: '/propietarios/',
    path: '/propietarios/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRanchosIdRoute = DashboardRanchosIdRouteImport.update({
  id: '/ranchos/$id',
  path: '/ranchos/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropietariosIdRoute = DashboardPropietariosIdRouteImport.update({
  id: '/propietarios/$id',
  path: '/propietarios/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/propietarios/$id': typeof DashboardPropietariosIdRoute
  '/dashboard/ranchos/$id': typeof DashboardRanchosIdRoute
  '/dashboard/propietarios/': typeof DashboardPropietariosIndexRoute
  '/dashboard/ranchos/': typeof DashboardRanchosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/propietarios/$id': typeof DashboardPropietariosIdRoute
  '/dashboard/ranchos/$id': typeof DashboardRanchosIdRoute
  '/dashboard/propietarios': typeof DashboardPropietariosIndexRoute
  '/dashboard/ranchos': typeof DashboardRanchosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/propietarios/$id': typeof DashboardPropietariosIdRoute
  '/dashboard/ranchos/$id': typeof DashboardRanchosIdRoute
  '/dashboard/propietarios/': typeof DashboardPropietariosIndexRoute
  '/dashboard/ranchos/': typeof DashboardRanchosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/propietarios/$id'
    | '/dashboard/ranchos/$id'
    | '/dashboard/propietarios/'
    | '/dashboard/ranchos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/propietarios/$id'
    | '/dashboard/ranchos/$id'
    | '/dashboard/propietarios'
    | '/dashboard/ranchos'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/propietarios/$id'
    | '/dashboard/ranchos/$id'
    | '/dashboard/propietarios/'
    | '/dashboard/ranchos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ranchos/': {
      id: '/dashboard/ranchos/'
      path: '/ranchos'
      fullPath: '/dashboard/ranchos/'
      preLoaderRoute: typeof DashboardRanchosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/propietarios/': {
      id: '/dashboard/propietarios/'
      path: '/propietarios'
      fullPath: '/dashboard/propietarios/'
      preLoaderRoute: typeof DashboardPropietariosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ranchos/$id': {
      id: '/dashboard/ranchos/$id'
      path: '/ranchos/$id'
      fullPath: '/dashboard/ranchos/$id'
      preLoaderRoute: typeof DashboardRanchosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/propietarios/$id': {
      id: '/dashboard/propietarios/$id'
      path: '/propietarios/$id'
      fullPath: '/dashboard/propietarios/$id'
      preLoaderRoute: typeof DashboardPropietariosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPropietariosIdRoute: typeof DashboardPropietariosIdRoute
  DashboardRanchosIdRoute: typeof DashboardRanchosIdRoute
  DashboardPropietariosIndexRoute: typeof DashboardPropietariosIndexRoute
  DashboardRanchosIndexRoute: typeof DashboardRanchosIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPropietariosIdRoute: DashboardPropietariosIdRoute,
  DashboardRanchosIdRoute: DashboardRanchosIdRoute,
  DashboardPropietariosIndexRoute: DashboardPropietariosIndexRoute,
  DashboardRanchosIndexRoute: DashboardRanchosIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
